export const GET_COUNTRIES = "GET_COUNTRIES"; //TODOS LOS PAÍSES

export const GET_BY_ID = "GET_BY_ID" // PAÍS POR ID

export const GET_BY_NAME = "GET_BY_NAME"; //BUSCAR POR EL NOMBRE

export const FILTER_BY_ACTIVITIES = "ORDER_BY_ACTIVITIES" //ORDENAR POR ACTIVIDADES

export const GET_ACTIVITIES = "GET_ACTIVITIES"// TRAER LAS ACRIVIDADES EXISTENTES

export const POST_ACTIVITIES= "POST_ACTIVITIES"// SELECCIONAR LAS ACTIVIDADES

export const FILTERS_COUNTRIES="FILTERS_COUNTRIES"// TODOOS LOS FILTROS TODOS